# Generated by Django 2.1.7 on 2022-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_auto_20221201_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
